ROWS, COLS = 20, 20
BLOCK_SIZE = 50
WIDTH, HEIGHT = COLS * BLOCK_SIZE, ROWS * BLOCK_SIZE
SQUARE_SIZE = WIDTH // COLS
TRACTOR_X = (ROWS - 1) * SQUARE_SIZE
TRACTOR_Y = (COLS - 1) * SQUARE_SIZE
DIRECTION_EAST = 2
DIRECTION_NORTH = 1
DIRECTION_SOUTH = 3
DIRECTION_WEST = 4
BACKGROUND = (147, 191, 71)
WHITE = (255, 255, 255)


DRY_SOIL_COST = 0
NORMAL_SOIL_COST = 2
WET_SOIL_COST = 10
